In [1]:
import numpy as np

In [2]:
np.arange(2,11).reshape((3,3))

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
li = []
n = int(input("number of values: "))
for i in range(n):
  li.append(int(input()))
np.array(li,dtype=float)

In [ ]:
np.array([input(),input(),input()],dtype=float)

In [ ]:
n1 = np.array([1,2,3])
n2 = np.append(n1,[int(input()),int(input())])
n2

In [ ]:
n2 = np.append(n2,l)

In [ ]:
n2

In [ ]:
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
n3 = np.append(n1,n2)

In [ ]:
n3

In [ ]:
n4 = np.array([3,4,5])
n5 = np.array([4,5,6])
sumArray = n4 + n5
sumArray

In [ ]:
np.add(n4,n5)

In [ ]:
n4 ** n5

In [ ]:
2 ** 4

In [34]:
list(range(1,11,2))

[1, 3, 5, 7, 9]

In [35]:
array1 = np.arange(10,91,10)
array1 = array1.reshape(3,3)
array1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [36]:
array1[0]

array([10, 20, 30])

In [37]:
array1[-1][-1]

90

In [ ]:
lis = [7,8,9,"hey"]

In [ ]:
lis[-1][-1]

In [38]:
arr1 = np.array([3,4,5])
arr2 = np.array([4,5,6])
exp = arr1 ** arr2
exp

array([   81,  1024, 15625], dtype=int32)

In [ ]:
a=[]
b=[]
n=int(input("enter length of array a:"))
for i in range(n):
    a.append(int(input()))
n=int(input("enter length of array b:"))
for i in range(n):
    b.append(int(input()))
x=np.array(a)
y=np.array(b)
sumarray = x+y

In [ ]:
sumarray

In [14]:
def fun1(t,v):
  return np.full(t,v)

print(fun1((2,5),8))

[[8 8 8 8 8]
 [8 8 8 8 8]]


In [15]:
lit = [[1,2,3],[4,5,6],[7,8,9]]
lit[0]

[1, 2, 3]

In [20]:
def fun2(arrays):
  sum = np.zeros(len(arrays[0]),dtype=int)
  for i in arrays:
    sum = sum + i
  return sum

In [21]:
fun2([np.array([1,2,3]),np.array([4,5,6]),np.array([7,8,9])])

array([12, 15, 18])

In [22]:
np.zeros((1,3),dtype=int)

array([[0, 0, 0]])

In [23]:
0.0 + 1

1.0

In [24]:
def top(matrix,N,M):
  return matrix[:N,:M]

mat = np.arange(1,10).reshape(3,3)
top(mat,1,2)

array([[1, 2]])

In [ ]:
matrix

In [27]:
def bottom(matrix,N,M):
  return matrix[-N:,-M:]

mat = np.arange(1,10).reshape(3,3)
bottom(mat,2,2)

array([[5, 6],
       [8, 9]])

In [28]:
def fun3(arr):
  return {'mean':arr.mean(),'std_dev':arr.std()}

fun3(np.array([1,2,3]))

{'mean': 2.0, 'std_dev': 0.816496580927726}

In [29]:
l1 = [1,2,3]
l1.append(4)
l1.append(5)

In [30]:
l1

[1, 2, 3, 4, 5]

In [31]:
l1.extend([6,7,8,9,10])
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]